# tytn/shenron:${VERSION}-onwards
FROM rust:1.88 AS builder
WORKDIR /build
COPY onwards/ ./
RUN cargo build --release

FROM debian:bookworm-slim
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /build/target/release/onwards /usr/local/bin/onwards
